---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Caroline Corr"
pagetitle: "PM1 Caroline Corr"

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin
---

::: {.callout-tip icon=false}

## Github Repo Link

[Caroline Corr's PM1 Repo](https://github.com/stat301-1-2024-fall/final-project-1-carolinecorr)

:::


## Data source

For my final project, I intend to do an EDA on data from the CBS show Survivor. 
I am sourcing this data from the Survivor (CBS) Dataset by Justin Veiner on kaggle.com.
This database has 3 main tables: contestant data, season data, and tribe data. For
my project, I intend to mainly focus on the contestant table.

[Survivor Data](https://www.kaggle.com/datasets/justinveiner/survivor-cbs-dataset?resource=download)

## Why this data

I am a huge fan of this show, and I have witnessed it change in so many ways over
the years, so much so that it seems impossible to pinpoint what qualities one
must have to win the show. I want to discover patterns between contestants who have
won the show in order to investigate what themes have endured throughout the 47 seasons of the show despite so many format changes and twists. Additionally, it has long
been speculated that because the show is won by winning the jury vote, racial and
social biases play a factor in deciding who will win the show. This dataset is
great because it features extensive data concerning the racial, ethnic, and sexual
identities of all of the contestants, so I am interested in uncovering the degree
at which these factors play a role in determining the winner.

## Data quality & complexity check


```{r}
#| label: quality-check
#| echo: false

library(tidyverse)

survivor_data <- read_csv("data/contestant_table.csv")
skimr::skim_without_charts(survivor_data)
glimpse(survivor_data)
```
This data mainly involves character and numeric data, and there are 32 variables
for me to consider! Although there are less than 1000 observations, I still think
this data should be complex enough given the wide array of variables to consider,
and the fact that many contestants have been on the show more than once. There does
appear to be a lot of missing data for the tribe variables and num_jury_votes, but
these are likely because some seasons do not have a second or third tribe, and 
contestants that do not make it to the finale do not receive jury votes. Some
tidying may be required to turn all of the race/ethnicity binary variables into one.

## Potential data issues

As previously mentioned, I do think I will need to use pivot_longer() to combine
a lot of the race/ethnicity variables into one variable that lists the contestants'
racial/ethnic identities. 